### PR TITLE
LCD UI elements consistency adjustments

### PR DESCRIPTION
**Pull request by taligentx**
Thanks for the extensive work to bring current versions of Marlin and new features to these printers! This PR is to address some LCD UI elements in the 5.8.0 release that seem to be inconsistent:

### Description

LCD-Panel/DGUS-root/TFT:
- 022_main: Bed current temp font size does not match other temps, increased font size.
- 036_preheat: fan speed font color does not match fan speed in other screens, changed font color.
- 084_setup_no_sensor: displays X-Twist setup but not a valid selection for no sensor firmware, removed.

LCD-Panel/Masters/ADVi3++5 LCD-Panel.sketch
- At least as of Sketch.app 100.3, some element widths are too small and overflow to two lines (°C symbol, Temperature labels, plus others).  Interestingly, the same elements render correctly in Lunacy but the updated sketch file renders correctly in both apps.
- Sensor Settings: Y-axis (-) pressed icon not set to pressed.
- Setup No Sensor - Shows 2. X-Twist but not used in no sensor firmware, removed.
- Widgets/LED/Output - marked as exportable but not used for firmware, unset exportable.
- Main: Bumped version number on screenshot

### Requirements

5.8.0

### Benefits

Adjusts LCD UI elements for consistency.

### Configurations

n/a

### Related Issues

n/a

### CODE REVIEW

**Comment by andrivet** [comment]
Thanks for the PR. I will review it in the next few days.

**Comment by andrivet** [comment]
Unfortunately, it is not technically possible to merge this PR. Binary files are not merge-friendly. So instead, I have manually made some of the modifications you proposed:

> 022_main: Bed current temp font size does not match other temps, increased font size.
Fixed

> 036_preheat: fan speed font color does not match fan speed in other screens, changed font color.
Fixed

084_setup_no_sensor: displays X-Twist setup but not a valid selection for no sensor firmware, removed.
> Fixed

> At least as of Sketch.app 100.3, some element widths are too small and overflow to two lines (°C symbol, Temperature labels, plus others). Interestingly, the same elements render correctly in Lunacy but the updated sketch file renders correctly in both apps.
Not sure of the problem, so this is not fixed.

Sensor Settings: Y-axis (-) pressed icon not set to pressed.
> Fixed

Setup No Sensor - Shows 2. X-Twist but not used in no sensor firmware, removed.
> Fixed

Widgets/LED/Output - marked as exportable but not used for firmware, unset exportable.
> This is indeed used by ADVi3++ so not modified

Main: Bumped version number on screenshot
> Used only in the user manual, it is already bumped to 6.0.0

I do not plan to backport those changes to 5.8.0, so they will be available with version 6.0.0.

**Comment by taligentx** [comment]
> Unfortunately, it is not technically possible to merge this PR. Binary files are not merge-friendly. So instead, I have manually made some of the modifications you proposed:

Good to hear about the fixes, and noted about the binary files.

> > At least as of Sketch.app 100.3, some element widths are too small and overflow to two lines (°C symbol, Temperature labels, plus others). Interestingly, the same elements render correctly in Lunacy but the updated sketch file renders correctly in both apps.
> > Not sure of the problem, so this is not fixed.

I'll grab a few screenshots and can follow this up in an Issue.

> Widgets/LED/Output - marked as exportable but not used for firmware, unset exportable.
> 
> > This is indeed used by ADVi3++ so not modified

As above, I'll follow this up in an Issue.

> Main: Bumped version number on screenshot
> 
> > Used only in the user manual, it is already bumped to 6.0.0
> 
> I do not plan to backport those changes to 5.8.0, so they will be available with version 6.0.0.

Sounds good, looking forward to it!

**Comment by andrivet** [comment]
Are you registered on ADVi3++ Community? If yes, can send me a private message there? Thans in advance.

**Pull request closed without merging**
