### PR TITLE
enable advanced pause functionality

### PR DESCRIPTION
**Pull request by SureshotM6**
These commits enable advanced pause functionality such as M600 Filament Change, M125 Park Head, LCD beeper support, and support for pausing/resuming USB prints from the LCD.

### CODE REVIEW

**Comment by andrivet** [comment]
Thank you for this PR. Lots of things. I will not incorporate them all (for ex. I am not sure of M300 support - there is only a buzzer in the panel) but several interesting ideas.

**Comment by Mooncabbage** [comment]
To clarify, what sort of buzzer is it? Is it the kind that has a built in oscillator circuit, which just takes power, or is it the kind they put in Arduino kits and such, which you can signal directly.

Not clear on the specifics of the M300 support, but some kind of audio output from gcode might be useful for signalling filament changes.

**Comment by andrivet** [comment]
Very simple, passive buzzer. You can only adjust the buzz time. Far from M300 requirements.

**Comment by SureshotM6** [comment]
I've been using the buzzer from gcode for notification when the print is complete, such as "M300 P100" followed by "G4 P200" repeated a few times.  Passing a frequency to M300 is optional, and not supported for this LCD buzzer as andrivet stated and in the commit message.

The main use case for lcd_buzz though is for the code in Marlin that already makes use of it, such as M600 Filament Change, which beeps a few times while waiting for user the user to insert the new filament (IIRC, 5 beeps over ~15 seconds, followed by 5 very quick beeps).  M125 also beeps once after parking the head.  Mesh bed leveling uses it as well, although that is disabled by default.  It probably would also be useful to stick a long beep into Temperature::_temp_error(), but it isn't there now.  M300 comes for free when lcd_buzz has been implemented.

In any case, it has been useful to me; perhaps it isn't to you though.  If you decide not to take some of these patches, I can just keep rebasing them in my private repository, which is fine by me.

**Comment by andrivet** [comment]
@SureshotM6 I have implemented buzzer in version 3.0.0 and I am implementing some other features you suggest. I have however a question: why a weak function?

**Comment by SureshotM6** [comment]
> why a weak function?

I wanted to add a generic implementation of lcd_advanced_pause_show_message() that will work on any printer, which could be overwritten by more specific implementations when required (which may do more than just print text messages).  This weak function is used by the i3+ in my commits.  However, if for example you were to compile Marlin for a printer which uses ULTIPANEL, the weak function would be automatically overwritten by ULTIPANEL's lcd_advanced_pause_show_message() implementation (which is not weak).  The linked binary will only include the non-weak implementation, so it should have no size impact.

It's a cleaner way of providing a generic implementation than using #ifndefs around the block, in my opinion.  Similar to a virtual function in C++, but works in C and resolved at link time.  An ifndef would need to be updated for every printer which did not use the generic implementation, but would also work.

I intended to submit that patch ("ultralcd: enable generic advanced pause messages for all LCDs") to upstream Marlin, but I just haven't gotten around it it yet.  I think it would be useful for other printers as well, which is why I tried to make it generic.

**Comment by andrivet** [comment]
Thanks for this PR. I have taken many ideas, but implemented differently (and sometimes with different choices). The structure code has also changed a lot since version 2.1 so it is not a 1:1 merge.

**Pull request closed without merging**
