### PR TITLE
MARK 2 SUPPORT

### PR DESCRIPTION
**Pull request by churd83**
i3 Mark 2 support....hopefully i got it right this time lol

### CODE REVIEW

**Comment by andrivet** [comment]
Not quite right, sorry:
1) You have created another PR. Please do not do that. It is far better to modify an existing PR. Otherwise it is confusing.
2) As it is, I can't merge your PR because it is only for Mark II, and not compatible with Mark I. It is required to have something compatible with both (ie. to use ifdefs to be able to compile for one or the other Mark).

So this is what I suggest: I will close both PR for the moment. After I finish version 4, I will take again a look and see if I can implement the changes in a future version. Sorry, but I have plenty of work.

**Comment by churd83** [comment]
That's fine, take my data and use it if you want to or trash it if you want to. I never claimed to be a coder. I just wanted to get the information to you for the Mark 2 printer. It's working great for me. The main file is the pins file and you can use it if you want. What I provided is to the extent of my knowledge. We pay you for support. I'm not going to do your work for you. If you want to use it, fine. If you don't want to use it, fine. I'm done here trying to help you with support for the Mark 2 printer.

**Comment by andrivet** [comment]
For info, I make my best to support Mark II in version 4.0.0 (and not later as I said). Of course, I will credit you in the firmware (unless you do not agree).

**Comment by churd83** [comment]
I wasn't pushing for immediate support. I knew you were going to support inductive sensors on the Mk1 and just figured you'd fit it in there when you create the menus for that. I should have just sent you the pins file for your reference

**Pull request closed without merging**
